# Generated by Django 4.2.3 on 2023-07-16 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Akala', '0002_product_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
    ]
