# Generated by Django 4.2.3 on 2023-07-16 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Akala', '0004_alter_product_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='basket_name',
        ),
    ]
