# Generated by Django 4.2.3 on 2023-07-16 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Akala', '0005_remove_basket_basket_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='user_id',
            new_name='basket_user',
        ),
    ]
