# Generated by Django 4.2.3 on 2023-07-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Akala', '0006_rename_user_id_basket_basket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
