# Generated by Django 4.2.3 on 2023-07-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Akala', '0008_pricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_list',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
