# Generated by Django 4.2.3 on 2023-07-22 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Akala', '0009_product_price_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_price', models.CharField(max_length=100)),
                ('my_date', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_list',
        ),
        migrations.DeleteModel(
            name='PriceHistory',
        ),
        migrations.AddField(
            model_name='product',
            name='price_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='Akala.price_history'),
        ),
    ]
