# Generated by Django 4.2.3 on 2023-07-22 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Akala', '0010_price_history_remove_product_price_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_history',
        ),
        migrations.AddField(
            model_name='price_history',
            name='my_product',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='product', to='Akala.product'),
        ),
        migrations.AlterField(
            model_name='price_history',
            name='my_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='price_history',
            name='my_price',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
