# Generated by Django 4.2.3 on 2023-07-23 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Akala', '0011_remove_product_price_history_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sold_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_sold', models.DecimalField(blank=True, decimal_places=100, max_digits=100, null=True)),
                ('date_sold', models.DateField()),
                ('products_sold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sold', to='Akala.product')),
            ],
        ),
    ]
