# Generated by Django 4.2.3 on 2023-07-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Akala', '0012_sold_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sold_products',
            name='price_sold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=99, null=True),
        ),
    ]
