# Generated by Django 4.2.3 on 2023-07-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Akala', '0014_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
